[servers]
    [servers.frps-entrypoint]
    domain = "dersand.net"
    port = 7303

    [servers.organa]
    domain = "dersand.net"
    port = 7304

    [servers.public-internet]
    domain = "dersand.net"
    port = 80

    [servers.public-internet-https]
    domain = "dersand.net"
    port = 443

